package se.springer.geotrain.components

import se.springer.geotrain.R

val countries = listOf(
    Country(listOf("Andorra"), WorldPart.EUROPE, "ad", R.drawable.ad),
    Country(listOf("Albania"), WorldPart.EUROPE,"al", R.drawable.al),
    Country(listOf("Algeria"), WorldPart.AFRICA,"dz", R.drawable.dz),
    Country(listOf("Angola"), WorldPart.AFRICA,"ao", R.drawable.ao),
    Country(listOf("Armenia"), WorldPart.EUROPE,"am", R.drawable.am),
    Country(listOf("Austria", "Österrike"), WorldPart.EUROPE,"at", R.drawable.at),
    Country(listOf("Barbados"), WorldPart.CENTRAL_AMERICA,"bb", R.drawable.bb),
    Country(listOf("Belgium", "Belgien"), WorldPart.EUROPE,"be", R.drawable.be),
    Country(listOf("Brazil", "Brasilien"), WorldPart.SOUTH_AMERICA,"br", R.drawable.br),
    Country(listOf("Canada", "Kanada"), WorldPart.NORTH_AMERICA,"ca", R.drawable.ca),
    Country(listOf("Chile"), WorldPart.SOUTH_AMERICA,"cl", R.drawable.cl),
    Country(listOf("Colombia"), WorldPart.SOUTH_AMERICA,"co", R.drawable.co),
    Country(listOf("Denmark", "Danmark"), WorldPart.EUROPE,"dk", R.drawable.dk),
    Country(listOf("Djibouti"), WorldPart.ALL,"dj", R.drawable.dj),
    Country(listOf("Democratic Republic of Congo", "Congo"), WorldPart.AFRICA,"cd", R.drawable.cd),
    Country(listOf("Cabo Verde", "Kap Verde"), WorldPart.AFRICA,"cv", R.drawable.cv),
    Country(listOf("Czech Republic", "Checkien"), WorldPart.EUROPE,"cz", R.drawable.cz),
    Country(listOf("Ecuador"), WorldPart.SOUTH_AMERICA,"ec", R.drawable.ec),
    Country(listOf("El Salvador"), WorldPart.CENTRAL_AMERICA,"sv", R.drawable.sv),
    Country(listOf("Falkland Islands"), WorldPart.ALL,"fk", R.drawable.fk),
    Country(listOf("France", "Frankrike"), WorldPart.EUROPE,"fr", R.drawable.fr),
    Country(listOf("Germany", "Tyskland"), WorldPart.EUROPE,"de", R.drawable.de),
    Country(listOf("Haiti"), WorldPart.CENTRAL_AMERICA,"ht", R.drawable.ht),
    Country(listOf("Honduras"), WorldPart.CENTRAL_AMERICA,"hn", R.drawable.hn),
    Country(listOf("Ireland", "Irland"), WorldPart.EUROPE,"ie", R.drawable.ie),
    Country(listOf("Iran"), WorldPart.ASIA,"ir", R.drawable.ir),
    Country(listOf("Jamaica"), WorldPart.CENTRAL_AMERICA,"jm", R.drawable.jm),
    Country(listOf("Japan"), WorldPart.ASIA,"jp", R.drawable.jp),
    Country(listOf("Jordan"), WorldPart.ASIA,"jo", R.drawable.jo),
    Country(listOf("Kazakhstan"), WorldPart.ASIA,"kz", R.drawable.kz),
    Country(listOf("Laos"), WorldPart.ASIA,"la", R.drawable.la),
    Country(listOf("Malaysia"), WorldPart.ASIA,"my", R.drawable.my),
    Country(listOf("Monaco"), WorldPart.EUROPE,"mc", R.drawable.mc),
    Country(listOf("Montenegro"), WorldPart.EUROPE,"me", R.drawable.me),
    Country(listOf("Mexico"), WorldPart.NORTH_AMERICA,"mx", R.drawable.mx),
    Country(listOf("Namibia"), WorldPart.AFRICA,"na", R.drawable.na),
    Country(listOf("Nicaragua"), WorldPart.CENTRAL_AMERICA,"ni", R.drawable.ni),
    Country(listOf("Niger"), WorldPart.AFRICA,"ne", R.drawable.ne),
    Country(listOf("North Korea"), WorldPart.ASIA,"kp", R.drawable.kp),
    Country(listOf("Panama"), WorldPart.CENTRAL_AMERICA,"pa", R.drawable.pa),
    Country(listOf("Paraguay"), WorldPart.SOUTH_AMERICA,"py", R.drawable.py),
    Country(listOf("Russia", "Ryssland"), WorldPart.ASIA,"ru", R.drawable.ru),
    Country(listOf("Saint Lucia"), WorldPart.CENTRAL_AMERICA,"lc", R.drawable.lc),
    Country(listOf("Somalia"), WorldPart.AFRICA,"so", R.drawable.so),
    Country(listOf("South Korea"), WorldPart.ASIA,"kr", R.drawable.kr),
    Country(listOf("Sweden", "Sverige", "Svea Rike"), WorldPart.EUROPE,"se", R.drawable.se),
    Country(listOf("Lithuania", "Litauen"), WorldPart.EUROPE,"lt", R.drawable.lt),
    Country(listOf("Tajikistan"), WorldPart.ASIA,"tj", R.drawable.tj),
    Country(listOf("Uganda"), WorldPart.AFRICA,"ug", R.drawable.ug),
    Country(listOf("Ukraine", "Ukraina"), WorldPart.EUROPE,"ua", R.drawable.ua),
    Country(listOf("United States of America", "United States", "USA"), WorldPart.NORTH_AMERICA,"us", R.drawable.us),

)