package se.springer.geotrain.components

import se.springer.geotrain.R

val countries = listOf(
    Country(listOf("Andorra"), WorldPart.EUROPE, "ad", R.drawable.ad),
    Country(listOf("Albania"), WorldPart.EUROPE,"al", R.drawable.al),
    Country(listOf("Algeria"), WorldPart.AFRICA,"dz", R.drawable.dz),
    Country(listOf("Angola"), WorldPart.AFRICA,"ao", R.drawable.ao),
    Country(listOf("Armenia"), WorldPart.EUROPE,"am", R.drawable.am),
    Country(listOf("Austria"), WorldPart.EUROPE,"at", R.drawable.at),
    Country(listOf("Barbados"), WorldPart.CENTRAL_AMERICA,"bb", R.drawable.bb),
    Country(listOf("Brazil"), WorldPart.SOUTH_AMERICA,"br", R.drawable.br),
    Country(listOf("Chile"), WorldPart.SOUTH_AMERICA,"cl", R.drawable.cl),
    Country(listOf("Colombia"), WorldPart.SOUTH_AMERICA,"co", R.drawable.co),
    Country(listOf("Denmark"), WorldPart.EUROPE,"dk", R.drawable.dk),
    Country(listOf("Democratic Republic of Congo", "Congo"), WorldPart.AFRICA,"cd", R.drawable.cd),
    Country(listOf("Czech Republic"), WorldPart.EUROPE,"cz", R.drawable.cz),
    Country(listOf("El Salvador"), WorldPart.CENTRAL_AMERICA,"sv", R.drawable.sv),
    Country(listOf("France"), WorldPart.EUROPE,"fr", R.drawable.fr),
    Country(listOf("Germany"), WorldPart.EUROPE,"de", R.drawable.de),
    Country(listOf("Haiti"), WorldPart.CENTRAL_AMERICA,"ht", R.drawable.ht),
    Country(listOf("Ireland"), WorldPart.EUROPE,"ie", R.drawable.ie),
    Country(listOf("Iran"), WorldPart.ASIA,"ir", R.drawable.ir),
    Country(listOf("Jamaica"), WorldPart.CENTRAL_AMERICA,"jm", R.drawable.jm),
    Country(listOf("Japan"), WorldPart.ASIA,"jp", R.drawable.jp),
    Country(listOf("Jordan"), WorldPart.ASIA,"jo", R.drawable.jo),
    Country(listOf("Monaco"), WorldPart.EUROPE,"mc", R.drawable.mc),
    Country(listOf("Montenegro"), WorldPart.EUROPE,"me", R.drawable.me),
    Country(listOf("Nicaragua"), WorldPart.CENTRAL_AMERICA,"ni", R.drawable.ni),
    Country(listOf("Niger"), WorldPart.AFRICA,"ne", R.drawable.ne),
    Country(listOf("North Korea"), WorldPart.ASIA,"kp", R.drawable.kp),
    Country(listOf("Panama"), WorldPart.CENTRAL_AMERICA,"pa", R.drawable.pa),
    Country(listOf("Russia"), WorldPart.ASIA,"ru", R.drawable.ru),
    Country(listOf("Saint Lucia"), WorldPart.CENTRAL_AMERICA,"lc", R.drawable.lc),
    Country(listOf("Somalia"), WorldPart.AFRICA,"so", R.drawable.so),
    Country(listOf("South Korea"), WorldPart.ASIA,"kr", R.drawable.kr),
    Country(listOf("Sweden", "Sverige", "Svea Rike"), WorldPart.EUROPE,"se", R.drawable.se),
    Country(listOf("Lithuania"), WorldPart.EUROPE,"lt", R.drawable.lt),
    Country(listOf("Namibia"), WorldPart.AFRICA,"na", R.drawable.na),
    Country(listOf("Tajikistan"), WorldPart.ASIA,"tj", R.drawable.tj),
    Country(listOf("Uganda"), WorldPart.AFRICA,"ug", R.drawable.ug),
    Country(listOf("Ukraine"), WorldPart.EUROPE,"ua", R.drawable.ua),
    Country(listOf("United States of America", "United States", "USA"), WorldPart.NORTH_AMERICA,"us", R.drawable.us),

)